GlanceImages.create_and_delete_image:
- args:
    container_format: bare
    disk_format: qcow2
    image_location: http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
  runner:
    concurrency: 1
    times: 1
    type: constant
  sla:
    failure_rate:
      max: 0
GlanceImages.create_and_list_image:
- args:
    container_format: bare
    disk_format: qcow2
    image_location: http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
  runner:
    concurrency: 1
    times: 1
    type: constant
  sla:
    failure_rate:
      max: 0 