# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

# ============================================================================
# Keepalived service
# ============================================================================
- name: "Stop keepalived {{ keepalived_name }}"
  # Stops the keepalived systemd service before reloading configuration
  ansible.builtin.service:
    name: "{{ keepalived_name }}"
    state: stopped
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _stop
  until: _stop is success
  retries: 5
  delay: 10
  listen:
    - Restart keepalived

- name: "Start keepalived {{ keepalived_name }}"
  # Starts and enables the keepalived systemd service
  ansible.builtin.service:
    name: "{{ keepalived_name }}"
    enabled: true
    state: started
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _start
  until: _start is success
  retries: 5
  delay: 10
  listen:
    - Restart keepalived