# Copyright (C) - LOW-LAYER
# Contact : contact@low-layer.com

---

# ============================================================================
# Create secret vault-role-id in Podman
# ============================================================================
- name: Retrieve Vault role_id dynamically using token
  # Get role_id from Vault using the provided token
  community.hashi_vault.vault_read:
    url: https://vault.internal
    path: auth/approle/role/vault-agent/role-id
  register: role_id_result
  no_log: true
  delegate_to: localhost
  become: false

- name: Set role_id fact
  ansible.builtin.set_fact:
    vault_role_id: "{{ role_id_result.data.data.role_id }}"
  no_log: true

- name: Create secret vault-role-id in Podman
  # Store Vault role_id secret for authentication in Podman
  containers.podman.podman_secret:
    state: present
    name: vault-role-id
    data: "{{ vault_role_id }}"
  notify:
    - Restart Vault Agent

# ============================================================================
# Create secret vault-secret-id in Podman
# ============================================================================
- name: Retrieve Vault secret_id dynamically using token
  # Generate a new secret_id from Vault for AppRole authentication
  community.hashi_vault.vault_write:
    url: https://vault.internal
    path: auth/approle/role/vault-agent/secret-id
    data: {}
  register: secret_id_result
  no_log: true
  delegate_to: localhost
  become: false

- name: Set secret_id fact
  ansible.builtin.set_fact:
    vault_secret_id: "{{ secret_id_result.data.data.secret_id }}"
  no_log: true

- name: Create secret vault-secret-id in Podman
  # Store Vault secret_id secret for authentication in Podman
  containers.podman.podman_secret:
    state: present
    name: vault-secret-id
    data: "{{ vault_secret_id }}"
  notify:
    - Restart Vault Agent