# Copyright (C) - LOW-LAYER
# Contact : contact@low-layer.com

---

# ============================================================================
# Deploy CA certificate
# ============================================================================
- name: "Deploy internal-CA certificate"
  # Copy internal CA certificate to system trust store
  ansible.builtin.copy:
    src:  "internal-ca.crt"
    dest: "{{ system_pki_ca_trust_anchor_path }}/internal-ca.crt"

- name: "Deploy kube-CA certificate"
  # Copy Kubernetes CA certificate to system trust store
  ansible.builtin.copy:
    src:  "kube-ca.crt"
    dest: "{{ system_pki_ca_trust_anchor_path }}/kube-ca.crt"

# ============================================================================
# Extract certificates
# ============================================================================
- name: "Extract certificates"
  # Update system CA trust
  ansible.builtin.shell: update-ca-trust extract