# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

argument_specs:
  main:
    short_description: "Configure Kubernetes runtime with CRI-O, CNI, and Cilium"
    description: |
      This role installs and configures the Kubernetes container runtime
      (CRI-O), networking (CNI), and Cilium plugin for Kubernetes clusters.

      Usage:
        - Install CRI-O and cri-tools at the specified version
        - Deploy CNI plugins to the correct path
        - Configure runtime settings for CRI-O
        - Deploy and configure Cilium as the networking plugin

      Notes:
        - Requires root privileges to install and configure system components
        - Tested with Fedora CoreOS and RHEL-like environments
        - CRI-O and CNI versions must match Kubernetes release compatibility

    author: "Astocanthus <contact@low-layer.com>"

    options:
      kubernetes_version_crio:
        type: "str"
        required: true
        description: "Version of CRI-O to install (e.g., 1.29)"

      kubernetes_version_cri_tools:
        type: "str"
        required: true
        description: "Version of cri-tools to install (e.g., 1.29)"

      kubernetes_version_cni:
        type: "str"
        required: true
        description: "Version of CNI plugins to install (e.g., 1.3.0)"

      runtime_crio_config_path:
        type: "str"
        required: true
        description: "Path to CRI-O main configuration file"

      runtime_cni:
        type: "dict"
        required: true
        description: "Configuration for CNI plugin installation and permissions"
        options:
          bin_path:
            type: "str"
            required: true
            description: "Path to install CNI binaries"
          net_config_path:
            type: "str"
            required: true
            description: "Path for storing CNI network configuration files"
          owner:
            type: "str"
            default: "root"
            description: "Owner of runtime configuration files"
          group:
            type: "str"
            default: "root"
            description: "Group of runtime configuration files"
          mode:
            type: "str"
            default: "0755"
            description: "Default file mode for runtime configuration files"
