# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

# ============================================================================
# Kube-apiserver service
# ============================================================================
- name: Stop kube-apiserver
  # Stops the kube-apiserver systemd service before reloading configuration
  ansible.builtin.service:
    name: kube-apiserver
    state: stopped
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _stop
  until: _stop is success
  retries: 5
  delay: 10
  listen:
    - Restart kube-apiserver

- name: Start kube-apiserver
  # Starts and enables the kube-apiserver systemd service
  ansible.builtin.service:
    name: kube-apiserver
    enabled: true
    state: started
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _start
  until: _start is success
  retries: 5
  delay: 10
  listen:
    - Restart kube-apiserver