apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/certs/kubernetes/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "{{ cluster_domain }}"
clusterDNS:
- "{{ kubernetes_cluster_dns_ip }}"
resolvConf: "{{ host_resolvconf_path }}"
containerRuntimeEndpoint: "{{ host_container_runtime_socket_path }}"
runtimeRequestTimeout: "10m"
tlsCertFile: "/certs/kubernetes/kubelet.pem"
tlsPrivateKeyFile: "/certs/kubernetes/kubelet.key"
serverTLSBootstrap: true
cgroupDriver: "{{ cgroup_driver }}"
tlsCipherSuites:
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384