# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

################################################################################
# General versions variables
################################################################################