# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

- name: Bootstrap controller hosts
  # ========================================================================
  # Controller node bootstrap
  # ========================================================================
  # Apply all roles necessary for Kubernetes controller nodes
  # This includes high availability, secret management, API server, controller manager, scheduler, CNI, and kubelet
  # Ensure that each component is installed and configured in the correct order
  become: yes
  gather_facts: yes
  hosts: k8s_controller
  roles:
    - keepalived                  # Provides HA via virtual IP
    - vault_agent                 # Manages certificates and encryption keys
    - haproxy                     # Load balancer for API server
    - kube_apiserver              # API server installation
    - kube_controller_manager     # Manages controllers for Kubernetes objects
    - kube_scheduler              # Schedules pods across nodes
    - kube_runtime                # Container runtime (CRI-O/CNI) configuration
    - kubelet                     # Node agent, ensures pods run properly