# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

################################################################################
# Group Variables for Vault Kubernetes certificates worker nodes
################################################################################

# Vault templates to apply for this group
vault_kubernetes_templates:
  - kubelet

# Disable creation of Kubernetes encryption key pair service accounts
vault_transit_kubernetes_sa: false