# Copyright (C) - LOW-LAYER
# Contact : contact@low-layer.com

---

# ============================================================================
# Create Kubernetes configuration directory
# ============================================================================
- name: Create kubernetes configuration directory
  # Ensure the main Kubernetes configuration directory exists with proper ownership and permissions
  ansible.builtin.file:
    path:  "{{ kubernetes_config['path'] }}"
    owner: "{{ kubernetes_config['owner'] }}"
    group: "{{ kubernetes_config['group'] }}"
    mode:  "{{ kubernetes_config['mode'] }}"
    state: directory

# ============================================================================
# Create Kubelet library directory
# ============================================================================
- name: Create kubelet library directory
  # Ensure the kubelet library directory exists with secure ownership and permissions
  ansible.builtin.file:
    path:  "{{ kubelet_lib['path'] }}"
    owner: "{{ kubelet_lib['owner'] }}"
    group: "{{ kubelet_lib['group'] }}"
    mode:  "{{ kubelet_lib['mode'] }}"
    state: directory

# ============================================================================
# Deploy kubelet configuration files
# ============================================================================
- name: Deploy kubelet config
  # Deploy configuration files for kubelet, including main config and kubelet.conf
  ansible.builtin.template:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    owner: "{{ kubernetes_config['owner'] }}"
    group: "{{ kubernetes_config['group'] }}"
    mode: '0750'
  with_items:
    - src:  "manifest/config.yaml"
      dest: "{{ kubernetes_config['path'] }}/kubelet-config.yaml"
    - src:  "conf/kubelet.conf"
      dest: "{{ kubernetes_config['path'] }}/kubelet.conf"
  notify:
    - Restart kubelet

# ============================================================================
# Deploy Podman systemd unit for kubelet
# ============================================================================
- name: Deploy Podman systemd unit for kubelet
  # Deploy the container unit file for kubelet to run under Podman systemd integration
  ansible.builtin.template:
    src:  "containers/kubelet.container"
    dest: "{{ quadlet_root_container_path }}/kubelet.container"
  notify:
    - Restart kubelet