# Copyright (C) - LOW-LAYER
# Contact : contact@low-layer.com

---

# ============================================================================
# VARIABLES VALIDATION
# ============================================================================

- name: "Validate configuration paths are absolute"
  assert:
    that:
      - kubernetes_config.path is match('^/')
      - kubelet_lib.path is match('^/')
      - vault_agent_certs_path is match('^/')
      - quadlet_root_container_path is match('^/')
      - host_resolvconf_path is match('^/')
      - host_container_runtime_path is match('^/')
    fail_msg: "❌ All paths must be absolute (start with /)"
    success_msg: "✅ All paths are absolute"

- name: "Validate socket path"
  assert:
    that:
      - host_container_runtime_socket_path is match('^unix://')
    fail_msg: "❌ Socket path must start with unix URI (start with unix://)"
    success_msg: "✅ Socket path must start with unix URI"

- name: "Validate node IP address"
  assert:
    that:
      - kubernetes_node_ip | ansible.utils.ipaddr
    fail_msg: "❌ Invalid node IP address: {{ kubernetes_node_ip }}"
    success_msg: "✅ Valid node IP address: {{ kubernetes_node_ip }}"

- name: "Validate Kubernetes cluster DNS IP"
  assert:
    that:
      - kubernetes_cluster_dns_ip | ansible.utils.ipaddr
    fail_msg: "❌ Invalid cluster DNS IP: {{ kubernetes_cluster_dns_ip }}"
    success_msg: "✅ Valid cluster DNS IP: {{ kubernetes_cluster_dns_ip }}"