# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

# ============================================================================
# Kube-scheduler service
# ============================================================================
- name: Stop kube-scheduler
  # Stops the kube-scheduler systemd service before reloading configuration
  ansible.builtin.service:
    name: kube-scheduler
    state: stopped
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _stop
  until: _stop is success
  retries: 5
  delay: 10
  listen:
    - Restart kube-scheduler

- name: Start kube-scheduler
  # Starts and enables the kube-scheduler systemd service
  ansible.builtin.service:
    name: kube-scheduler
    enabled: true
    state: started
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _start
  until: _start is success
  retries: 5
  delay: 10
  listen:
    - Restart kube-scheduler
