CinderVolumes.create_and_delete_volume:
- args:
    size: 1
  runner:
    concurrency: 1
    times: 1
    type: constant
  sla:
    failure_rate:
      max: 0
- args:
    size:
      max: 5
      min: 1
  runner:
    concurrency: 1
    times: 1
    type: constant
  sla:
    failure_rate:
      max: 0 