# Copyright (C) - LOW-LAYER
# Cilium Helm values - Config for CoreOS + CRI-O + Istio Ambient

# =============================================================================
# API SERVER CONNECTION
# =============================================================================
# Kubernetes API server endpoint configuration for Cilium agent connectivity
k8sServiceHost: "kube.low-layer.internal"
k8sServicePort: "6443"

# =============================================================================
# CNI CONFIGURATION
# =============================================================================
# Container Network Interface setup for manual CNI management
cni:
  install: true
  binPath: "/opt/cni/bin"
  confPath: "/etc/cni/net.d"
  exclusive: false

# =============================================================================
# CORE NETWORKING
# =============================================================================
# Base networking configuration with kube-proxy replacement
kubeProxyReplacement: true
routingMode: "tunnel"
enableIPv4Masquerade: true

# =============================================================================
# LOADBALANCER CONFIGURATION
# =============================================================================
# Layer 2 announcements for LoadBalancer services
l2announcements:
  enabled: true

# =============================================================================
# IPAM CONFIGURATION
# =============================================================================
# IP Address Management with cluster-wide pod CIDR
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.0.0.0/16"]
    clusterPoolIPv4MaskSize: 24

# =============================================================================
# BPF CONFIGURATION
# =============================================================================
# Berkeley Packet Filter mounting for CoreOS compatibility
bpf:
  autoMount:
    enabled: true
  mountPath: "/sys/fs/bpf"

# =============================================================================
# ISTIO AMBIENT COMPATIBILITY
# =============================================================================
# Disabled features to ensure compatibility with Istio Ambient mesh
envoy:
  enabled: false
l7Proxy: false
socketLB:
  enabled: true
  hostNamespaceOnly: true
nodePort:
  enabled: true

# =============================================================================
# NETWORK POLICY CONFIGURATION
# =============================================================================
# Network policy enforcement disabled for Istio Ambient mesh
policyEnforcementMode: "never"
k8sNetworkPolicy:
  enabled: false
bandwidthManager:
  enabled: false
installNoConntrackIptablesRules: false

# =============================================================================
# NODE ASSIGNMENT CONFIGURATION
# =============================================================================
# Pod scheduling and tolerations for control plane deployment
tolerations:
  - operator: Exists

nodeSelector: {}

# =============================================================================
# OPERATOR CONFIGURATION
# =============================================================================
# Cilium operator deployment settings for control plane nodes
operator:
  replicas: 1
  tolerations:
    - operator: Exists
  nodeSelector: 
    node-role.kubernetes.io/control-plane: ""

# =============================================================================
# NODE INITIALIZATION
# =============================================================================
# Node initialization configuration for all cluster nodes
nodeinit:
  tolerations:
    - operator: Exists
  nodeSelector: {}

# =============================================================================
# MONITORING CONFIGURATION
# =============================================================================
# Hubble observability platform disabled to save resources
hubble:
  enabled: false