# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

argument_specs:
  main:
    short_description: "Deploy and configure HashiCorp Vault Agent with Podman"
    description: |
      This role configures and deploys HashiCorp Vault Agent in a containerized
      environment using Podman and systemd Quadlet units.

      It manages configuration directories, AppRole authentication secrets,
      certificate templates, and PKI trust store integration for Kubernetes
      certificate management.

      Usage:
        - Ensure Vault server is accessible and AppRole is configured.
        - Ensure proper CA certificates are available in files/ directory.
        - Run with appropriate Vault token for AppRole operations.

      Notes:
        - Requires root privileges for systemd and container operations.
        - Uses Podman secrets for secure credential storage.
        - Integrates with system PKI trust store for certificate validation.
    author: "LOW-LAYER <contact@low-layer.com>"

    options:
      vault_agent_config_path:
        type: "str"
        required: true
        description: "Path to Vault Agent configuration directory"

      vault_agent_templates_path:
        type: "str"
        required: true
        description: "Path to Vault Agent templates directory"

      vault_agent_certs_path:
        type: "str"
        required: true
        description: "Path where Vault Agent will write certificates"

      vault_agent_uid:
        type: "int"
        required: true
        description: "User ID for Vault Agent configuration files ownership"

      vault_agent_gid:
        type: "int"
        required: true
        description: "Group ID for Vault Agent configuration files ownership"

      vault_agent_templats_applications_list:
        type: "list"
        elements: "str"
        required: true
        description: "List of applications for which certificate directories will be created"

      vault_kubernetes_templates:
        type: "list"
        elements: "str"
        required: true
        description: "List of Kubernetes certificate templates to be rendered by Vault Agent"

      vault_transit_kubernetes_sa:
        type: "bool"
        required: false
        default: false
        description: "Enable Kubernetes service account key management via Vault Transit"

      quadlet_root_container_path:
        type: "str"
        required: true
        description: "Root path for Podman Quadlet container unit files"

      system_pki_ca_trust_path:
        type: "str"
        required: true
        description: "CA trust store source directory (contains source/anchors/ for custom CAs, extracted/ subdirectory generated by update-ca-trust command)"

      system_ssl_certs_path:
        type: "str"
        required: true
        description: "Application CA lookup directory (symlinks pointing to extracted/ files, used by curl/wget/openssl for certificate validation)"

      system_pki_ca_trust_anchor_path:
        type: "str"
        required: true
        description: "Custom CA certificates directory (where to add .crt/.pem files before running update-ca-trust to rebuild the trust store)"