# Copyright (C) - LOW-LAYER - 2025
# Contact : contact@low-layer.com

---

################################################################################
# Group Variables for Kubernetes cluster API
################################################################################

# Virtual IP and FQDN for the internal Kubernetes API server
vip_kubernetes_api_server:
  internal:
    ip: 192.168.3.251
    netmask: 24
    fqdn: "kube.low-layer.internal"

# Kubernetes API server configuration
kubernetes_api_server_port: 6443